import { DocCell, DocTable, Token } from "@/components/doc-table"
import { descriptionFor } from "@/lib/api-overrides"

/**
 * Renders the props tables generated by scripts/generate-component-api.mjs.
 *
 * Pages pass a family and a part name rather than hand-writing rows, so a table
 * cannot drift from the type it documents. scripts/check-generated-api.mjs
 * fails CI when the checked-in data no longer matches the source.
 */

export type GeneratedProp = {
  name: string
  type: string
  typeFull?: string
  required: boolean
  default: string | null
  description: string
  source: "own" | "base-ui" | "other"
}

export type GeneratedPart = {
  name: string
  props: GeneratedProp[]
  reactPassthrough: number
  universal: number
}

export type GeneratedFamily = {
  module: string
  parts: GeneratedPart[]
}

/**
 * Which underlying element a family's React passthrough resolves to, for the
 * footnote. Only needed where the count is non-zero.
 */
const PASSTHROUGH_ELEMENT: Record<string, string> = {
  button: "<button>",
  input: "<input>",
  textarea: "<textarea>",
  table: "<table>",
}

const PropsRow = ({
  prop,
  part,
}: {
  prop: GeneratedProp
  part: string
}) => {
  // Base UI documents its own props; cva variant props have no declaration site
  // to carry JSDoc, so those descriptions come from the overrides file.
  const description = prop.description || descriptionFor(part, prop.name)

  return (
    <tr>
      <DocCell mono>
        {prop.name}
        {prop.required ? (
          <span className="text-fg-quaternary" title="Required">
            {" *"}
          </span>
        ) : null}
      </DocCell>
      <DocCell mono>
        <span title={prop.typeFull ?? prop.type}>{prop.type}</span>
      </DocCell>
      <DocCell mono>{prop.default ?? "—"}</DocCell>
      <DocCell>{description || "—"}</DocCell>
    </tr>
  )
}

export const PropsTable = ({
  family,
  part,
}: {
  family: GeneratedFamily
  part: string
}) => {
  const entry = family.parts.find((item) => item.name === part)

  if (!entry) {
    throw new Error(
      `PropsTable: "${part}" is not in the generated API for "${family.module}". Run npm run generate:api.`,
    )
  }

  if (entry.props.length === 0) {
    return (
      <p className="text-md mt-4 max-w-3xl text-fg-secondary">
        <Token>{part}</Token> takes no props of its own beyond the shared
        styling props.
      </p>
    )
  }

  const passthrough = PASSTHROUGH_ELEMENT[family.module]

  return (
    <>
      <DocTable headers={["Prop", "Type", "Default", "Description"]}>
        {entry.props.map((prop) => (
          <PropsRow key={prop.name} prop={prop} part={part} />
        ))}
      </DocTable>
      {entry.reactPassthrough > 0 ? (
        <p className="text-sm mt-2 text-fg-tertiary">
          Also accepts all standard{" "}
          {passthrough ? <Token>{passthrough}</Token> : "element"} attributes.
        </p>
      ) : null}
    </>
  )
}

/**
 * Every part of a family in one table. This is what the 34 pages whose API
 * section was an untyped anatomy list get instead.
 */
export const PartsTable = ({ family }: { family: GeneratedFamily }) => (
  <DocTable headers={["Part", "Props", "Description"]}>
    {family.parts.map((part) => (
      <tr key={part.name}>
        <DocCell mono>{part.name}</DocCell>
        <DocCell>{part.props.length || "—"}</DocCell>
        <DocCell>{descriptionFor(part.name, null) || "—"}</DocCell>
      </tr>
    ))}
  </DocTable>
)

/** Stated once per page rather than repeated across every part's table. */
export const StylingPropsNote = () => (
  <p className="text-sm mt-2 text-fg-tertiary">
    Every part also accepts <Token>className</Token>, <Token>style</Token>, and{" "}
    <Token>render</Token> for styling and element substitution.
  </p>
)
