export const foundations = [
  { href: "/", label: "Introduction" },
  { href: "/colors", label: "Colors" },
  { href: "/typography", label: "Typography" },
  { href: "/structure", label: "Structure" },
  { href: "/materials", label: "Materials" },
  { href: "/icons", label: "Icons" },
] as const

export const components = [
  { href: "/components/accordion", label: "Accordion" },
  { href: "/components/alert-dialog", label: "Alert dialog" },
  { href: "/components/avatar", label: "Avatar" },
  { href: "/components/badge", label: "Badge" },
  { href: "/components/button", label: "Button" },
  { href: "/components/calendar", label: "Calendar" },
  { href: "/components/card", label: "Card" },
  { href: "/components/chart", label: "Chart" },
  { href: "/components/checkbox", label: "Checkbox" },
  { href: "/components/collapsible", label: "Collapsible" },
  { href: "/components/combobox", label: "Combobox" },
  { href: "/components/dialog", label: "Dialog" },
  { href: "/components/drawer", label: "Drawer" },
  { href: "/components/input", label: "Input" },
  { href: "/components/menu", label: "Menu" },
  { href: "/components/number-field", label: "Number field" },
  { href: "/components/otp-field", label: "OTP field" },
  { href: "/components/popover", label: "Popover" },
  { href: "/components/progress", label: "Progress" },
  { href: "/components/radio-group", label: "Radio group" },
  { href: "/components/scroll-area", label: "Scroll area" },
  { href: "/components/select", label: "Select" },
  { href: "/components/separator", label: "Separator" },
  { href: "/components/slider", label: "Slider" },
  { href: "/components/switch", label: "Switch" },
  { href: "/components/tabs", label: "Tabs" },
  { href: "/components/textarea", label: "Textarea" },
  { href: "/components/toggle", label: "Toggle" },
  { href: "/components/tooltip", label: "Tooltip" },
] as const

export const upcomingComponents = [] as const
