export type TypeSpecimen = {
  token: string
  family: string
  size: string
  lineHeight: string
  weight: string
  /** Letter spacing; Apps SDK scale is currently 0em throughout. */
  tracking?: string
  sample: string
  className: string
  group: "heading" | "body" | "code"
}

/** Apps SDK scale from heading-2xl → text-2xs (excludes 5xl–3xl and 3xs). */
export const typeScale: TypeSpecimen[] = [
  {
    token: "heading-2xl-sans",
    family: "Söhne",
    size: "36px",
    lineHeight: "42px",
    weight: "500",
    sample: "Heading 2xl",
    className: "heading-2xl-sans",
    group: "heading",
  },
  {
    token: "heading-2xl-serif",
    family: "Signifier",
    size: "36px",
    lineHeight: "42px",
    weight: "500",
    sample: "Heading 2xl",
    className: "heading-2xl-serif",
    group: "heading",
  },
  {
    token: "heading-xl-sans",
    family: "Söhne",
    size: "32px",
    lineHeight: "38px",
    weight: "500",
    sample: "Heading xl",
    className: "heading-xl-sans",
    group: "heading",
  },
  {
    token: "heading-xl-serif",
    family: "Signifier",
    size: "32px",
    lineHeight: "38px",
    weight: "500",
    sample: "Heading xl",
    className: "heading-xl-serif",
    group: "heading",
  },
  {
    token: "heading-lg-sans",
    family: "Söhne",
    size: "24px",
    lineHeight: "28px",
    weight: "500",
    sample: "Heading lg",
    className: "heading-lg-sans",
    group: "heading",
  },
  {
    token: "heading-lg-serif",
    family: "Signifier",
    size: "24px",
    lineHeight: "28px",
    weight: "500",
    sample: "Heading lg",
    className: "heading-lg-serif",
    group: "heading",
  },
  {
    token: "heading-md",
    family: "Söhne",
    size: "20px",
    lineHeight: "26px",
    weight: "500",
    sample: "Heading md",
    className: "heading-md",
    group: "heading",
  },
  {
    token: "heading-sm",
    family: "Söhne",
    size: "18px",
    lineHeight: "26px",
    weight: "500",
    sample: "Heading sm",
    className: "heading-sm",
    group: "heading",
  },
  {
    token: "heading-xs",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "500",
    sample: "Heading xs",
    className: "heading-xs",
    group: "heading",
  },
  {
    token: "text-lg",
    family: "Söhne",
    size: "18px",
    lineHeight: "29px",
    weight: "400",
    sample: "Text lg",
    className: "text-lg",
    group: "body",
  },
  {
    token: "text-lg-strong",
    family: "Söhne",
    size: "18px",
    lineHeight: "29px",
    weight: "500",
    sample: "Text lg",
    className: "text-lg-strong",
    group: "body",
  },
  {
    token: "text-md",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "400",
    sample: "Text md",
    className: "text-md",
    group: "body",
  },
  {
    token: "text-md-strong",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "500",
    sample: "Text md",
    className: "text-md-strong",
    group: "body",
  },
  {
    token: "text-sm",
    family: "Söhne",
    size: "14px",
    lineHeight: "20px",
    weight: "400",
    sample: "Text sm",
    className: "text-sm",
    group: "body",
  },
  {
    token: "text-sm-strong",
    family: "Söhne",
    size: "14px",
    lineHeight: "20px",
    weight: "500",
    sample: "Text sm",
    className: "text-sm-strong",
    group: "body",
  },
  {
    token: "text-xs",
    family: "Söhne",
    size: "12px",
    lineHeight: "18px",
    weight: "400",
    sample: "Text xs",
    className: "text-xs",
    group: "body",
  },
  {
    token: "text-xs-strong",
    family: "Söhne",
    size: "12px",
    lineHeight: "18px",
    weight: "500",
    sample: "Text xs",
    className: "text-xs-strong",
    group: "body",
  },
  {
    token: "font-mono text-sm",
    family: "Söhne Mono",
    size: "14px",
    lineHeight: "20px",
    weight: "400",
    sample: "bg-brand-primary",
    className: "font-mono text-sm",
    group: "code",
  },
  {
    token: "text-brand-primary",
    family: "Söhne Mono",
    size: "14px",
    lineHeight: "20px",
    weight: "400",
    sample: "brand",
    className: "font-mono text-sm text-brand-primary",
    group: "code",
  },
  {
    token: "text-destructive",
    family: "Söhne Mono",
    size: "14px",
    lineHeight: "20px",
    weight: "400",
    sample: "danger",
    className: "font-mono text-sm text-destructive",
    group: "code",
  },
]
