export type TypeSpecimen = {
  token: string
  family: string
  size: string
  lineHeight: string
  weight: string
  /** Letter spacing; Apps SDK scale is currently 0em throughout. */
  tracking?: string
  sample: string
  className: string
  group: "heading" | "body"
}

/** Apps SDK scale from heading-2xl → text-2xs (excludes 5xl–3xl and 3xs). */
export const typeScale: TypeSpecimen[] = [
  {
    token: "heading-2xl-sans",
    family: "Söhne",
    size: "36px",
    lineHeight: "42px",
    weight: "600",
    sample: "Heading 2xl",
    className: "heading-2xl-sans",
    group: "heading",
  },
  {
    token: "heading-2xl-serif",
    family: "Signifier",
    size: "36px",
    lineHeight: "42px",
    weight: "600",
    sample: "Heading 2xl",
    className: "heading-2xl-serif",
    group: "heading",
  },
  {
    token: "heading-xl-sans",
    family: "Söhne",
    size: "32px",
    lineHeight: "38px",
    weight: "600",
    sample: "Heading xl",
    className: "heading-xl-sans",
    group: "heading",
  },
  {
    token: "heading-xl-serif",
    family: "Signifier",
    size: "32px",
    lineHeight: "38px",
    weight: "600",
    sample: "Heading xl",
    className: "heading-xl-serif",
    group: "heading",
  },
  {
    token: "heading-lg-sans",
    family: "Söhne",
    size: "24px",
    lineHeight: "28px",
    weight: "600",
    sample: "Heading lg",
    className: "heading-lg-sans",
    group: "heading",
  },
  {
    token: "heading-lg-serif",
    family: "Signifier",
    size: "24px",
    lineHeight: "28px",
    weight: "600",
    sample: "Heading lg",
    className: "heading-lg-serif",
    group: "heading",
  },
  {
    token: "heading-md",
    family: "Söhne",
    size: "20px",
    lineHeight: "26px",
    weight: "600",
    sample: "Heading md",
    className: "heading-md",
    group: "heading",
  },
  {
    token: "heading-sm",
    family: "Söhne",
    size: "18px",
    lineHeight: "26px",
    weight: "600",
    sample: "Heading sm",
    className: "heading-sm",
    group: "heading",
  },
  {
    token: "heading-xs",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "600",
    sample: "Heading xs",
    className: "heading-xs",
    group: "heading",
  },
  {
    token: "text-lg",
    family: "Söhne",
    size: "18px",
    lineHeight: "29px",
    weight: "400",
    sample: "Text lg",
    className: "text-lg",
    group: "body",
  },
  {
    token: "text-lg-strong",
    family: "Söhne",
    size: "18px",
    lineHeight: "29px",
    weight: "500",
    sample: "Text lg",
    className: "text-lg-strong",
    group: "body",
  },
  {
    token: "text-md",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "400",
    sample: "Text md",
    className: "text-md",
    group: "body",
  },
  {
    token: "text-md-strong",
    family: "Söhne",
    size: "16px",
    lineHeight: "24px",
    weight: "500",
    sample: "Text md",
    className: "text-md-strong",
    group: "body",
  },
  {
    token: "text-sm",
    family: "Söhne",
    size: "14px",
    lineHeight: "20px",
    weight: "400",
    sample: "Text sm",
    className: "text-sm",
    group: "body",
  },
  {
    token: "text-sm-strong",
    family: "Söhne",
    size: "14px",
    lineHeight: "20px",
    weight: "500",
    sample: "Text sm",
    className: "text-sm-strong",
    group: "body",
  },
  {
    token: "text-xs",
    family: "Söhne",
    size: "12px",
    lineHeight: "18px",
    weight: "400",
    sample: "Text xs",
    className: "text-xs",
    group: "body",
  },
  {
    token: "text-xs-strong",
    family: "Söhne",
    size: "12px",
    lineHeight: "18px",
    weight: "500",
    sample: "Text xs",
    className: "text-xs-strong",
    group: "body",
  },
  {
    token: "text-2xs",
    family: "Söhne",
    size: "10px",
    lineHeight: "14px",
    weight: "400",
    sample: "Text 2xs",
    className: "text-2xs",
    group: "body",
  },
  {
    token: "text-2xs-strong",
    family: "Söhne",
    size: "10px",
    lineHeight: "14px",
    weight: "500",
    sample: "Text 2xs",
    className: "text-2xs-strong",
    group: "body",
  },
]

export const fontFamilies = [
  {
    cssVar: "--font-sans",
    className: "font-sans",
    font: "Söhne",
    usage: "Default UI and body. Paragraphs, controls, and general content.",
  },
  {
    cssVar: "--font-display",
    className: "font-display",
    font: "Signifier",
    usage: "Serif display. Use with heading-*-serif for editorial titles.",
  },
  {
    cssVar: "--font-mono",
    className: "font-mono",
    font: "Söhne Mono",
    usage: "Monospace. Code, tokens, and technical identifiers.",
  },
] as const

export const headingScaleRows = [
  {
    token: "heading-2xl-sans / heading-2xl-serif",
    font: "Söhne / Signifier",
    size: "36px (2xl)",
    lineHeight: "42px",
    weight: "600",
    usage: "Page titles and hero headings. Use sparingly.",
  },
  {
    token: "heading-xl-sans / heading-xl-serif",
    font: "Söhne / Signifier",
    size: "32px (xl)",
    lineHeight: "38px",
    weight: "600",
    usage: "Major section headings.",
  },
  {
    token: "heading-lg-sans / heading-lg-serif",
    font: "Söhne / Signifier",
    size: "24px (lg)",
    lineHeight: "28px",
    weight: "600",
    usage: "Subsection headings.",
  },
  {
    token: "heading-md",
    font: "Söhne",
    size: "20px (md)",
    lineHeight: "26px",
    weight: "600",
    usage: "Card titles, dialog headers.",
  },
  {
    token: "heading-sm",
    font: "Söhne",
    size: "18px (sm)",
    lineHeight: "26px",
    weight: "600",
    usage: "Small headings and list headers.",
  },
  {
    token: "heading-xs",
    font: "Söhne",
    size: "16px (xs)",
    lineHeight: "24px",
    weight: "600",
    usage: "Compact headings in dense UI.",
  },
] as const

export const bodyScaleRows = [
  {
    token: "text-lg / text-lg-strong",
    size: "18px (lg)",
    lineHeight: "29px",
    weight: "400 / 500",
    usage: "Lead paragraphs and intro copy.",
  },
  {
    token: "text-md / text-md-strong",
    size: "16px (md)",
    lineHeight: "24px",
    weight: "400 / 500",
    usage: "Default body text and labels.",
  },
  {
    token: "text-sm / text-sm-strong",
    size: "14px (sm)",
    lineHeight: "20px",
    weight: "400 / 500",
    usage: "Captions, helper text, button labels.",
  },
  {
    token: "text-xs / text-xs-strong",
    size: "12px (xs)",
    lineHeight: "18px",
    weight: "400 / 500",
    usage: "Footnotes, timestamps, badges.",
  },
  {
    token: "text-2xs / text-2xs-strong",
    size: "10px (2xs)",
    lineHeight: "14px",
    weight: "400 / 500",
    usage: "Dense metadata and compact chrome.",
  },
] as const
